backend:
  name: github
  repo: 18F/resources.data.gov
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: develop
  use_graphql: true

publish_mode: editorial_workflow
show_preview_links: true

media_folder: "pages/assets/media"
public_folder: "/assets/media"

collections:
  - name: "resources"
    preview_path: "resources/{{slug}}"
    label: "Resources"
    create: true
    folder: "pages/_resources/"
    slug: "{{fields.slug}}"

    fields:
      - label: "name"
        name: "name"
        widget: "string"
        hint: "name of the resource"
        required: true

      - label: "slug"
        name: "slug"
        widget: "string"
        hint: "slug link (part that comes at the very end of a url)"
        required: true

      - label: "description"
        name: "description"
        widget: "text"
        hint: "short description of the resource"
        required: true

      - label: "source"
        name: "source"
        widget: "string"
        hint: "who created the resource"
        required: true

      - label: "category"
        name: "category"
        widget: "relation"
        valueField: "category_name"
        searchFields: ["category_name"]
        hint: "category of the resource"
        collection: "categories"
        multiple: false
        required: true

      - label: "tags"
        name: "tags"
        widget: "relation"
        collection: "keywords"
        multiple: true
        hint: "tags for this resource"
        valueField: "name"
        searchFields: ["name"]
        required: true

      - label: "policy_tags"
        name: "policy tags"
        widget: "relation"
        collection: "policy_tags"
        multiple: true
        hint: "policy tags for this resource"
        valueField: "policy_name"
        searchFields: ["policy_name"]
        required: false

      - label: "format"
        name: "format"
        widget: "string"
        hint: "format or type of resource"
        required: false

      - label: "link"
        name: "link to resource"
        widget: "markdown"
        hint: "link to the resource"
        required: false

      - label: "details"
        name: "details"
        widget: "markdown"
        hint: "detailed description of the resource"
        required: false

      - label: "examples"
        name: "examples"
        widget: "markdown"
        hint: "descriptions of or links to how this resource has been used"
        required: false

      - label: "layout"
        name: "layout"
        widget: "select"
        options: ["resource"]
        default: "resource"
        hint: "the layout template to use"
        required: true

      - label: "toc"
        name: "toc"
        widget: "boolean"
        default: true
        hint: "autogenerate a table of contents"
        required: true

  - name: "summaries"
    label: "Summaries"
    create: true
    folder: "pages/_summaries/"
    slug: "{{fields.slug}}"

    fields:
      - label: "name"
        name: "name"
        widget: "string"
        hint: "name of the resource summary"
        required: true

      - label: "slug"
        name: "slug"
        widget: "string"
        hint: "slug link (part that comes at the very end of a url)"
        required: true

      - label: "description"
        name: "description"
        widget: "text"
        hint: "short description of the resource summary"
        required: true

      - label: "source"
        name: "source"
        widget: "string"
        hint: "who created the resource summary"
        required: true

      - label: "category"
        name: "category"
        widget: "relation"
        valueField: "category_name"
        searchFields: ["category_name"]
        hint: "category of the resource summary"
        collection: "categories"
        multiple: false
        required: true

      - label: "tags"
        name: "tags"
        widget: "relation"
        collection: "keywords"
        multiple: true
        hint: "tags for this resource summary"
        valueField: "name"
        searchFields: ["name"]
        required: true

      - label: "policy_tags"
        name: "policy tags"
        widget: "relation"
        collection: "policy_tags"
        multiple: true
        hint: "policy tags for this resource summary"
        valueField: "policy_name"
        searchFields: ["policy_name"]
        required: false

      - label: "format"
        name: "format"
        widget: "string"
        hint: "format or type of resource"
        required: false

      - label: "link"
        name: "link to resource summary"
        widget: "markdown"
        hint: "link to the resource"
        required: true

  - name: "categories"
    label: "Categories"
    create: true
    folder: "pages/_categories/"
    identifier_field: "category_name"

    fields:
      - label: "name"
        name: "category_name"
        widget: "string"
        hint: "name of the category"
        required: true

      - label: "description"
        name: "description"
        widget: "text"
        hint: "short description of the category"
        required: true

      - label: "layout"
        name: "layout"
        widget: "select"
        options: ["resource_category"]
        default: "resource_category"
        hint: "the layout template to use"
        required: true

      - label: "navigation section"
        name: "primary_nav_section"
        widget: "select"
        options: ["Resources", "Communities"]
        default: "Resources"
        hint: "the navigation section this category belongs to"
        required: true

      - label: "show on front page"
        name: "show_on_front_page"
        widget: "boolean"
        default: true
        hint: "show this category on the front page?"
        required: true

  - name: "keywords"
    label: "Keywords"
    create: true
    folder: "pages/_keywords/"
    slug: "{{fields.slug}}"

    fields:
      - label: "name"
        name: "name"
        widget: "string"
        hint: "name of the keyword"
        required: true

      - label: "slug"
        name: "slug"
        widget: "string"
        hint: "slug link (part that comes at the very end of a url)"
        required: true

      - label: "layout"
        name: "layout"
        widget: "select"
        options: ["keyword"]
        default: "keyword"
        hint: "the layout template to use"
        required: true

      - label: "toc"
        name: "toc"
        widget: "boolean"
        default: true
        hint: "autogenerate a table of contents"
        required: true

  - name: "policy_tags"
    label: "Policy Tags"
    create: true
    folder: "pages/_policy_tags/"
    slug: "{{fields.slug}}"

    fields:
      - label: "policy name"
        name: "policy_name"
        widget: "string"
        hint: "name of the keyword"
        required: true

      - label: "slug"
        name: "slug"
        widget: "string"
        hint: "slug link (part that comes at the very end of a url)"
        required: true

      - label: "layout"
        name: "layout"
        widget: "select"
        options: ["policy_tag"]
        default: "policy_tag"
        hint: "the layout template to use"
        required: true

      - label: "toc"
        name: "toc"
        widget: "boolean"
        default: true
        hint: "autogenerate a table of contents"
        required: true
