name: QA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1'

jobs:
  qa:
    uses: gsa/data.gov/.github/workflows/static-site-qa-template.yml@main
    with:
      site_url: https://resources.data.gov
      issue_number: 811
